name: Pylint Checker

on:
  push:
    branches: [ "develop", "staging", "main" ]
  pull_request:
    branches: [ "develop", "staging", "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint

    - name: Run Pylint on all Python files
      id: pylint
      run: |
        pylint_output=$(pylint **/*.py)
        echo "$pylint_output"

        # Extract the score from the pylint output
        score=$(echo "$pylint_output" | grep "Your code has been rated" | awk '{print $7}' | sed 's|/10||')

        # Check if the score is below the threshold
        if (( $(echo "$score < 10" | bc -l) )); then
            echo "Pylint score is below the threshold of 5.0. Failing the job."
            exit 1
        fi