name: Pylint Checker

on:
  push:
    branches: [ "develop", "staging", "main" ]
  pull_request:
    branches: [ "develop", "staging", "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # You can specify any version you need
        
    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        
    - name: Run Pylint on all Python files
      run: |
        pylint **/*.py || true  # This allows the workflow to continue even if pylint finds issues
